trigger:
  branches:
    include:
    - master
  tags:
    include:
    - v*


pool:
  vmImage: 'Windows-latest'
steps:
- checkout: self
- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: $(System.DefaultWorkingDirectory)\build.ps1
  displayName: 'Build everything'
