trigger:
  branches:
    include:
    - master
  tags:
    include:
    - v*

stages:

- stage: Build
  displayName: 'Build'
  jobs:
  - deployment: Build
    pool:
      vmImage: 'Windows-latest'
    steps:
    - checkout: self
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: $(System.DefaultWorkingDirectory)\build.ps1
      displayName: 'Build everything'
