[package]
name = "juliaup"
version = "0.1.0"
edition = "2018"
default-run = "juliaup"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
dirs = "3.0"
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
semver = "1.0"
anyhow = "1.0"
tempfile = "3.0"
reqwest = { version = "0.11", features = ["blocking"] }
flate2 = "1.0"
tar = "0.4"

[build-dependencies]
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
