name: Build and Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  build-launcher:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x64, x86]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore Juliaup.sln

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /property:Configuration=Release /property:Platform=${{ matrix.platform }} Juliaup.sln

  build-juliaup:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x64]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: julia-actions/setup-julia@v1
      with:
        version: 1.6.1
        arch: ${{matrix.platform}}
    - name: Run PackageCompiler
      run: |
        julia .\Juliaup\build.jl
  
  prepare-bundled-julia:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [{form1: 'x64', form2: 'win64'}, {form1: 'x86', form2: 'win32'}]
    steps:
    - uses: actions/checkout@v2
    - name: Read version info
      id: bundledversion
      run: |
        $versions = Get-Content versions.json | ConvertFrom-Json
        [version]$bundledVersion = $versions.JuliaAppPackage.BundledJuliaVersion
        $bundledVersionAsString = $versions.JuliaAppPackage.BundledJuliaVersion
        $bundledMajorVersionAsString = $bundledVersion.Major
        $bundledMinorVersionAsString = $bundledVersion.Minor
        echo "::set-output name=bundledVersion::$bundledVersionAsString"
        echo "::set-output name=bundledMajorVersion::$bundledMajorVersionAsString"
        echo "::set-output name=bundledMinorVersion::$bundledMinorVersionAsString"
    - name: Create folders
      run: |
        mkdir -Force build\downloads
        mkdir -Force build\juliaversions\${{matrix.platform.form1}}
    - name: Download Julia archive
      run: |
        if (-Not (Test-Path ".\build\downloads\julia-${{steps.bundledversion.outputs.bundledVersion}}-${{matrix.platform.form2}}.tar.gz"))
        {
          Invoke-WebRequest "https://julialang-s3.julialang.org/bin/winnt/${{matrix.platform.form1}}/${{steps.bundledversion.outputs.bundledMajorVersion}}.${{steps.bundledversion.outputs.bundledMinorVersion}}/julia-${{steps.bundledversion.outputs.bundledVersion}}-${{matrix.platform.form2}}.tar.gz" -OutFile "build\downloads\julia-${{steps.bundledversion.outputs.bundledVersion}}-${{matrix.platform.form2}}.tar.gz"
        }
    - name: Extract Julia archive
      run: |
        if (-Not (Test-Path "build\juliaversions\${{matrix.platform.form1}}\julia-$($bundledVersionAsString)"))
        {
          tar -xvzf "build\downloads\julia-$($bundledVersion)-${{matrix.platform.form2}}.tar.gz" -C build\juliaversions\${{matrix.platform.form1}}
        }
