name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.ref_name || github.run_id }} 
  cancel-in-progress: true

jobs:

  test-juliaup:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        target: [
          x86_64-pc-windows-msvc,
          x86_64-apple-darwin,
          x86_64-unknown-linux-gnu,
          x86_64-unknown-linux-musl,
          i686-pc-windows-msvc,
          ]
        include:
          - target: x86_64-pc-windows-msvc
            os: windows
            features: dummy
            rustflags:
          - target: x86_64-apple-darwin
            os: macos
            features: dummy
            rustflags:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu
            features: dummy
            rustflags:
          - target: x86_64-unknown-linux-musl
            os: ubuntu
            features: dummy
            rustflags: -C target-feature=+crt-static
          - target: i686-pc-windows-msvc
            os: windows
            features: dummy
            rustflags:
    steps:
    - uses: actions/checkout@v3
    - if: ${{ contains(matrix.target, "-musl") }}
      run: apt-get install musl-tools
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        target: ${{matrix.target}}
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --target ${{matrix.target}} --features ${{matrix.features}}
      env:
        CARGO_TARGET_x86_64-unknown-linux-musl: ${{matrix.rustflags}}
        CARGO_TARGET_i686-unknown-linux-musl: ${{matrix.rustflags}}
        CARGO_TARGET_aarch64-unknown-linux-musl: ${{matrix.rustflags}}
