name: Test

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

jobs:

  test-juliaup:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        target: [
          x86_64-pc-windows-msvc,
          x86_64-apple-darwin,
          x86_64-unknown-linux-gnu,
          i686-pc-windows-msvc,
          ]
        include:
          - target: x86_64-pc-windows-msvc
            os: windows
            features: dummy
          - target: x86_64-apple-darwin
            os: macos
            features: dummy
          - target: x86_64-unknown-linux-gnu
            os: ubuntu
            features: dummy
          - target: i686-pc-windows-msvc
            os: windows
            features: dummy
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        target: ${{matrix.target}}
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --target ${{matrix.target}} --features ${{matrix.features}}
