name: Update Version DB

on:
  workflow_dispatch:

jobs:

  update-versiondb:
    runs-on: ubuntu-latest
    environment: dev-channel
    steps:
    - uses: actions/checkout@v3
    - uses: julia-actions/setup-julia@v1
      with:
        version: 1.6
    - name: Update Version DB
      run: |
        julia scripts/versiondb/updateversiondb.jl scriptoutputfolder
    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --cache-control public,max-age=2678400 --metadata-directive REPLACE
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'scriptoutputfolder/newversiondbs'
    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --cache-control public,max-age=0 --metadata-directive REPLACE
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'scriptoutputfolder/versionfile'
